disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Harry Duke"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"
description = "Harry Duke's personal portfolio"

[params.author]
headline = "Computer Science for Games graduate focused on technical games programming, from gameplay systems and AI behaviour to physics and engine development."
bioTitle = "Hi, I'm Harry"
bio = "I have recently graduated with a First Class B.Sc. (Hons) degree in Computer Science for Games from the University of Brighton. I specialise in technical games programming and have worked on projects involving engine development, physics simulations, AI behaviour, and gameplay programming. I have experience using a variety of languages and tools for game development such as C++, Unreal Engine, Unity, and SDL. I have developed game prototypes with teams of up to five people, strengthening my teamwork and project management skills. I am currently seeking a graduate job as a games programmer."
bioDownload = "CV"
name = "Harry Duke"
links = [
    { email = "mailto:harryjduke@gmail.com" },
    { github = "https://github.com/harryjduke" },
    { linkedin = "https://www.linkedin.com/in/harryduke/" },
]
